#!/bin/sh
#
# Initialize USB...
# Author: Miloš Polakovič
#

case "$1" in
  start)
        echo "Loading USB kernel modules..."
        modprobe usb_storage
        modprobe ohci-pci
	modprobe snd_bcm2835
        echo "Available devices: "; lsusb
        ;;
  *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
